Automated_dep_CI_Demo/src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_To_Name__c</fullName>
        <label>Additional To Name</label>
        <length>220</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Name__c</fullName>
        <label>Bill To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grand_Total__c</fullName>
        <label>Grand Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Quote_To_Name__c</fullName>
        <label>Quote  Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Name__c</fullName>
        <label>Ship To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_and_Handling__c</fullName>
        <label>Shipping and Handling</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>open</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Syncing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Syncing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Automated_dep_CI_Demo/src/classes/convertQuoteintoOrder.cls
public class convertQuoteintoOrder{


public convertQuoteintoOrder(){
}
public PageReference createOrder(){
system.debug('11111111111111111');

Id recordId = ApexPages.currentPage().getParameters().get('Id');

system.debug('22222222222222'+recordId );
quote qte= [select AdditionalName,Opportunity.Account.Name,Opportunity.Name,Description, Contact.FirstName,Contact.LastName,BillingName,Discount,Email,ExpirationDate,GrandTotal,Phone,Name,QuoteNumber,QuoteToName,ShippingHandling,ShippingName,Status,Subtotal,IsSyncing,Tax,TotalPrice from quote where id=:recordId];
system.debug('44444444444444'+qte );
//if(qte.size()>0){
system.debug('333333333333333');
Orders__c ord = new Orders__c();

ord.Additional_To_Name__c=qte.AdditionalName;
ord.Bill_To_Name__c=qte.BillingName;
ord.Discount__c=qte.Discount;
ord.Email__c=qte.Email;
ord.Expiration_Date__c=qte.ExpirationDate;
ord.Grand_Total__c=qte.GrandTotal;
ord.Phone__c=qte.Phone;
//ord.Quote_Number__c=qte.QuoteNumber;
ord.Quote_To_Name__c=qte.Name;
ord.Shipping_and_Handling__c=qte.ShippingHandling;
ord.Ship_To_Name__c=qte.ShippingName;
ord.Status__c=qte.Status;
ord.Subtotal__c=qte.Subtotal;
ord.Syncing__c=qte.IsSyncing;
ord.Tax__c=qte.Tax;
ord.Account_Name__c=qte.Opportunity.Account.Name;
ord.Opportunity_Name__c=qte.Opportunity.Name;
ord.Contact_Name__c=qte.Contact.FirstName+qte.Contact.LastName;
ord.Description__c=qte.Description;


insert ord;
system.debug('5555555555'+ord.Id);
//string url= 'https://ap1.salesforce.com/a0R/o';
PageReference pageRef = new PageReference('/'+ord.Id);
pageRef.setRedirect(true);
return pageRef;

}
}